from pathlib import Path
import json,base64
r=Path(__file__).resolve().parent
p=r.parents[1]/'experiments/382-cli-batch-matting/packed'
d=json.loads((p/'animation.json').read_text());d['atlas']='data:image/png;base64,'+base64.b64encode((p/'animation.png').read_bytes()).decode()
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sprute — First steps</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f7f5ed;color:#283d31;font-family:system-ui,sans-serif;overflow:hidden}header{position:absolute;top:30px;left:40px;right:40px;display:flex;justify-content:space-between;align-items:center;z-index:2}.brand{font-size:23px;font-weight:800;letter-spacing:-1px}.tag{font-size:12px;letter-spacing:2px;color:#657366}canvas{width:100vw;height:100vh;display:block;touch-action:none}#intro{position:absolute;left:7vw;top:28vh;max-width:370px;pointer-events:none}h1{font-size:clamp(34px,4.5vw,66px);line-height:1.17;letter-spacing:-3px;margin:12px 0 22px}p{font-size:17px;line-height:1.7;color:#627064}button,a{pointer-events:auto;border:0;border-radius:24px;background:#294d37;color:white;padding:15px 25px;font:600 15px system-ui;cursor:pointer;text-decoration:none}#hud{position:absolute;bottom:30px;left:0;width:100%;text-align:center;pointer-events:none;color:#607264;font-size:14px}kbd{border:1px solid #bfccbd;background:#fff9;border-radius:5px;padding:3px 7px;margin:2px}#status{position:absolute;right:40px;bottom:30px;font-size:12px;color:#617365}#reset{position:absolute;right:40px;top:82px;background:transparent;color:#526650;border:1px solid #a8b9a3;padding:8px 15px}#note{position:absolute;bottom:65px;left:0;width:100%;text-align:center;font-size:11px;color:#7a8578;pointer-events:none}@media(max-width:700px){#intro{top:16vh;left:8vw;width:75vw}h1{font-size:38px}header{left:24px;right:24px}#status{display:none}}</style>
<header><span class="brand">sprute<span style="color:#7ca96c">.</span></span><span class="tag">YOUR CHARACTER, ALIVE</span></header><button id="reset">처음으로</button>
<canvas id="world" aria-label="8방향 캐릭터 이동 체험"></canvas><section id="intro"><span class="tag">JIN, THIS ONE IS FOR YOU</span><h1>그림 밖으로,<br>첫 걸음.</h1><p>네가 만든 캐릭터야.<br>이제 직접 움직여봐.</p><button id="start">움직여 보기 ↗</button></section>
<div id="hud"><kbd>↑</kbd><kbd>←</kbd><kbd>↓</kbd><kbd>→</kbd> 또는 WASD · 바닥을 클릭해도 돼</div><div id="note">실제 생성된 8방향 걷기 데모 · 멈춤은 정지 프레임 · 새 이미지 실시간 생성 화면은 아니에요</div><div id="status">S · READY</div>
<script>const data=DATA;const c=document.querySelector('canvas'),ctx=c.getContext('2d'),img=new Image();let w,h,x,y,dir='S',elapsed=0,last=0,started=false,target=null,steps=0;const keys=new Set(),prints=[];let nextPrint=0;
function resize(){w=innerWidth;h=innerHeight;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);if(x===undefined){x=w*.65;y=h*.58}else{x=Math.max(65,Math.min(w-65,x));y=Math.max(120,Math.min(h-100,y))}}addEventListener('resize',resize);resize();
function begin(){started=true;document.querySelector('#intro').style.display='none';c.focus()}document.querySelector('#start').onclick=begin;document.querySelector('#reset').onclick=()=>{started=false;target=null;keys.clear();x=w*.65;y=h*.58;dir='S';elapsed=0;prints.length=0;document.querySelector('#intro').style.display='block'};
const movementKeys=['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'];addEventListener('keydown',e=>{if(movementKeys.includes(e.key.toLowerCase())){e.preventDefault();begin();target=null;keys.add(e.key.toLowerCase())}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());c.onpointerdown=e=>{begin();target={x:e.clientX,y:e.clientY}};
function frame(d,t){const track=data.animations[d];let total=track.reduce((n,f)=>n+f.durationMs,0),v=t%total;return track.find(f=>(v-=f.durationMs)<0)||track[0]}
function tick(t){const dt=Math.min((t-last)/1000||0,.05);last=t;let dx=0,dy=0;if(started){dx=Number(keys.has('arrowright')||keys.has('d'))-Number(keys.has('arrowleft')||keys.has('a'));dy=Number(keys.has('arrowdown')||keys.has('s'))-Number(keys.has('arrowup')||keys.has('w'));if(target){dx=target.x-x;dy=target.y-y;if(Math.hypot(dx,dy)<5){target=null;dx=dy=0}}}let moving=Math.hypot(dx,dy)>0;if(moving){const n=Math.hypot(dx,dy);dx/=n;dy/=n;const dirs=['E','SE','S','SW','W','NW','N','NE'];dir=dirs[(Math.round(Math.atan2(dy,dx)/(Math.PI/4))+8)%8];x=Math.max(70,Math.min(w-70,x+dx*150*dt));y=Math.max(160,Math.min(h-100,y+dy*150*dt));elapsed+=dt*1000;if(t>nextPrint){prints.push({x,y,t});nextPrint=t+160;steps++}}while(prints.length&&t-prints[0].t>3000)prints.shift();
ctx.fillStyle='#edf0e2';ctx.fillRect(0,0,w,h);let g=ctx.createRadialGradient(w*.65,h*.5,40,w*.6,h*.5,w*.7);g.addColorStop(0,'#e2edd5');g.addColorStop(1,'#f8f5ed');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
for(let i=0;i<110;i++){let px=((i*7919)%1000)/1000*w,py=130+((i*3571)%1000)/1000*(h-200);ctx.fillStyle=i%7===0?'#d6bd75':'#b8cba4';ctx.globalAlpha=.45;ctx.fillRect(px,py,2,4);if(i%7===0)ctx.fillRect(px-2,py-1,6,2)}ctx.globalAlpha=1;
for(const p of prints){ctx.globalAlpha=Math.max(0,(1-(t-p.t)/3000)*.15);ctx.fillStyle='#57734a';ctx.beginPath();ctx.ellipse(p.x,p.y,4,2,0,0,7);ctx.fill()}ctx.globalAlpha=1;if(target){ctx.strokeStyle='#789a62';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(target.x,target.y,12,5,0,0,7);ctx.stroke()}
ctx.fillStyle='#82966a35';ctx.beginPath();ctx.ellipse(x,y+1,30,9,0,0,7);ctx.fill();if(img.complete&&img.naturalWidth){const f=frame(dir,moving?elapsed:0),size=230;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,f.x,f.y,f.width,f.height,x-size/2,y-size*.85,size,size)}document.querySelector('#status').textContent=dir+' · '+(moving?'WALKING':'STANDING');window.spruteDemo={x,y,direction:dir,moving,steps,ready:!!img.naturalWidth};requestAnimationFrame(tick)}img.src=data.atlas;requestAnimationFrame(tick);</script></html>'''
(r/'index.html').write_text(html.replace('DATA',json.dumps(d)),encoding='utf8')
