export function animationPreviewHtml(data: unknown): string {
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sprute animation preview</title><style>
body{font:16px system-ui;margin:24px;background:#171a20;color:#eee}button,select{font:inherit;padding:8px;margin:4px}button[aria-pressed=true]{outline:3px solid #59d7cc}canvas{display:block;image-rendering:pixelated;width:100%;height:auto}#grid{display:grid;grid-column:1/-1;grid-template-columns:repeat(8,minmax(0,1fr));gap:8px}#grid button{padding:4px;min-width:0;align-self:start}#detail,#referenceCanvas{max-width:512px;height:min(512px,40vw);object-fit:contain}.layout{display:grid;grid-template-columns:repeat(2,minmax(0,512px));gap:24px;align-items:start}.layout>div{min-width:0}#scrub{width:min(680px,100%)}textarea{display:block;box-sizing:border-box;width:min(680px,100%);height:70px}p{max-width:850px}#error,#notesError{color:#ffaaaa}#noteList button{max-width:100%;text-align:left;overflow-wrap:anywhere}@media(max-width:700px){body{margin:16px}#grid{grid-template-columns:repeat(4,minmax(0,1fr))}.layout{gap:12px}h2{font-size:18px}}
</style>
<h1>Animation preview</h1><p>Choose a direction to compare the same playback time. Check feet, changing details and the last-to-first frame. Exporting an animation does not approve its quality.</p>
<button id="play" disabled>Play</button><button id="prev" disabled>Previous frame</button><button id="next" disabled>Next frame</button>
<label>Speed <select id="speed"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option></select></label>
<label>Background <select id="background"><option value="#181824">Dark</option><option value="#ffffff">White</option><option value="#55aa66">Green</option></select></label>
<p><input id="scrub" type="range" min="0" value="0" aria-label="Frame" disabled> <output id="status">Loading…</output></p><p id="error" role="alert"></p>
<div class="layout"><div id="grid"></div><div><h2 id="heading">S</h2><canvas id="detail"></canvas></div><div id="referencePanel" hidden><h2>Original standing pose</h2><canvas id="referenceCanvas"></canvas><p>Same direction, before animation. Compare face, clothes and accessories; size and pose may differ.</p></div></div>
<p id="mode"></p><label id="noteTarget" for="note">Note for this direction and frame</label><textarea id="note" maxlength="4000" disabled></textarea><button id="saveNote" disabled>Save note</button><button id="export">Download notes</button><span id="saved"></span><p><label>Load review notes <input id="importNotes" type="file" accept="application/json,.json" disabled></label></p><p id="notesError" role="alert"></p><ul id="noteList"></ul>
<script id="animation-data" type="application/json">${JSON.stringify(data).replaceAll('<', '\\u003c')}</script>
<script>
const data=JSON.parse(document.getElementById('animation-data').textContent),$=id=>document.getElementById(id),dirs=data.directions,tiles={},notes=[],image=new Image(),timelines={};
const referenceImage=data.reference?new Image():null;let referenceReady=false;
let ready=false,running=false,elapsed=0,last=0,selected='S',draftTarget=null;
for(const d of dirs){let time=0;timelines[d]=data.tracks[d].map(f=>{const item={...f,time};time+=f.durationMs;return item;});}
const total=d=>{const f=timelines[d].at(-1);return f.time+f.durationMs;},maxTime=Math.max(...dirs.map(total));
function frameAt(d){const t=data.loop?elapsed%total(d):Math.min(elapsed,total(d));const i=timelines[d].findIndex(f=>t<f.time+f.durationMs);return i<0?data.count-1:i;}
function paint(canvas,d){const c=canvas.getContext('2d'),f=timelines[d][frameAt(d)];c.clearRect(0,0,data.width,data.height);c.imageSmoothingEnabled=false;c.drawImage(image,f.x,f.y,f.width,f.height,0,0,data.width,data.height);canvas.style.background=$('background').value;}
function paintReference(){if(!referenceReady)return;const canvas=$('referenceCanvas'),c=canvas.getContext('2d'),w=data.reference.width,h=data.reference.height;c.clearRect(0,0,w,h);c.imageSmoothingEnabled=false;c.drawImage(referenceImage,dirs.indexOf(selected)*w,0,w,h,0,0,w,h);canvas.style.background=$('background').value;}
function notePosition(){return {direction:selected,frame:frameAt(selected),timeMs:elapsed};}
function showNoteTarget(){const target=draftTarget||notePosition();$('noteTarget').textContent='Note for '+target.direction+', frame '+(target.frame+1)+(draftTarget?' (fixed while editing)':'');}
function draw(){if(!ready)return;for(const d of dirs)paint(tiles[d],d);paint($('detail'),selected);paintReference();$('heading').textContent=selected;$('scrub').value=frameAt(selected);$('status').textContent=(frameAt(selected)+1)+' / '+data.count+' · '+Math.round(elapsed)+' ms';showNoteTarget();}
function renderNotes(){const list=$('noteList');list.replaceChildren();for(const note of notes){const item=document.createElement('li'),button=document.createElement('button');button.textContent=note.direction+' · frame '+(note.frame+1)+': '+note.text;button.onclick=()=>{selected=note.direction;for(const btn of $('grid').children)btn.setAttribute('aria-pressed',String(btn.dataset.direction===selected));seek(note.frame);};item.append(button);list.append(item);}$('saved').textContent=notes.length+' notes (download before closing)';}
function stop(){running=false;$('play').textContent='Play';}
function seek(i){stop();i=data.loop?(i+data.count)%data.count:Math.max(0,Math.min(data.count-1,i));elapsed=timelines[selected][i].time;draw();}
function tick(now){if(running){elapsed+=(now-last)*Number($('speed').value);if(!data.loop&&elapsed>=maxTime){elapsed=maxTime;stop();}draw();}last=now;requestAnimationFrame(tick);}
for(const d of dirs){const b=document.createElement('button');b.dataset.direction=d;b.setAttribute('aria-label',d+' direction');b.setAttribute('aria-pressed',String(d===selected));const c=document.createElement('canvas');c.width=data.width;c.height=data.height;const label=document.createElement('span');label.textContent=d;b.append(label,c);b.onclick=()=>{selected=d;for(const btn of $('grid').children)btn.setAttribute('aria-pressed',String(btn.dataset.direction===d));draw();};$('grid').append(b);tiles[d]=c;}
$('detail').width=data.width;$('detail').height=data.height;$('scrub').max=data.count-1;$('mode').textContent=data.loop?'Loop enabled. Matching playback times do not prove matching foot phases.':'Plays once and stops on the last frame.';
$('play').onclick=()=>{if(running)stop();else{if(!data.loop&&elapsed>=maxTime)elapsed=0;running=true;last=performance.now();$('play').textContent='Pause';}};
$('prev').onclick=()=>seek(frameAt(selected)-1);$('next').onclick=()=>seek(frameAt(selected)+1);$('scrub').oninput=()=>seek(Number($('scrub').value));$('background').onchange=draw;
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
$('note').onfocus=()=>{stop();};
$('note').oninput=()=>{stop();if($('note').value.trim()){draftTarget??=notePosition();}else{draftTarget=null;}showNoteTarget();};
$('saveNote').onclick=()=>{if(!ready||!$('note').value.trim())return;if(notes.length>=1000||$('note').value.length>4000){$('notesError').textContent='Keep reviews within 1000 notes and each note within 4000 characters.';return;}$('notesError').textContent='';stop();notes.push({...(draftTarget||notePosition()),text:$('note').value});$('note').value='';draftTarget=null;showNoteTarget();renderNotes();};
$('importNotes').onchange=async()=>{stop();$('notesError').textContent='';const file=$('importNotes').files?.[0];if(!file)return;try{if(file.size>1024*1024)throw new Error('Notes file exceeds 1 MiB.');const saved=JSON.parse(await file.text());if(saved.atlasSha256!==data.atlasSha256||saved.metadataSha256!==data.metadataSha256)throw new Error('These notes belong to a different animation.');if(saved.referenceSha256!==undefined&&saved.referenceSha256!==data.reference?.sha256)throw new Error('These notes use a different original reference.');if(!Array.isArray(saved.notes)||saved.notes.length>1000)throw new Error('Expected at most 1000 review notes.');const incoming=saved.notes.map(n=>{if(!n||!dirs.includes(n.direction)||!Number.isSafeInteger(n.frame)||n.frame<0||n.frame>=data.count||!Number.isFinite(n.timeMs)||n.timeMs<0||typeof n.text!=='string'||!n.text.trim()||n.text.length>4000)throw new Error('Invalid direction, frame, time or text in notes.');return {direction:n.direction,frame:n.frame,timeMs:n.timeMs,text:n.text};});const key=n=>JSON.stringify([n.direction,n.frame,n.timeMs,n.text]),seen=new Set(notes.map(key)),fresh=[];for(const note of incoming){if(!seen.has(key(note))){seen.add(key(note));fresh.push(note);}}if(notes.length+fresh.length>1000)throw new Error('This review would exceed 1000 notes.');notes.push(...fresh);renderNotes();}catch(error){$('notesError').textContent=error instanceof Error?error.message:'Could not load notes.';}finally{$('importNotes').value='';}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({status:'unreviewed',atlasSha256:data.atlasSha256,metadataSha256:data.metadataSha256,referenceSha256:data.reference?.sha256,notes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sprute-review-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
if(referenceImage){$('referencePanel').hidden=false;$('referenceCanvas').width=data.reference.width;$('referenceCanvas').height=data.reference.height;referenceImage.onload=()=>{referenceReady=true;paintReference();};referenceImage.onerror=()=>{$('error').textContent='Could not decode the original reference sheet.';};referenceImage.src=data.reference.image;}
image.onload=()=>{ready=true;for(const id of ['play','prev','next','scrub','note','saveNote','importNotes'])$(id).disabled=false;draw();requestAnimationFrame(tick);};image.onerror=()=>{$('error').textContent='Could not decode the embedded atlas.';};image.src=data.atlas;
</script></html>`;
}
